### ISSUE TITLE
Is it possible to run 2D Delaunay Triangulation on GPU using your library?

### ISSUE THREAD

**Issue by YuxinxinChen** [ashwin/gDel3D#12]
Hi gDel3D team,

I would like to run 2D Delaunay Triangulation on GPU given a set of vertices or an arbitrary triangulation. Is it possible to run it using your library? If yes, is there a significant performance loss to run 2D DT on your 3D DT library?

I am also wondering which algorithm you use for Delaunay Triangulation, Lawson's based algorithm, or Voronoi based algorithm?

Thanks a lot!

-Yuxin

**Comment by ashwin** [comment]
@YuxinxinChen If you just want 2D DT, it is better to use a 2D DT algorithm. For example, the gDel2D algorithm: https://www.comp.nus.edu.sg/~tants/delaunay2DDownload.html

For information on gDel3D see its paper: https://www.comp.nus.edu.sg/~tants/gdel3d.html

**Comment by YuxinxinChen** [comment]
Thanks a lot!
