### ISSUE TITLE
Compile error on CUDA 9.1

### ISSUE THREAD

**Issue by sina-masnadi** [ashwin/gDel3D#2]
I get this error when I try to compile it using CUDA 9.1 on Ubuntu 16.04:

`/gDel3D/GDelFlipping/src/gDel3D/GpuDelaunay.cu(839): error: namespace "thrust" has no member "gather"`

**Comment by ashwin** [comment]
@sina-masnadi I've added the `thrust/gather.h` header file. Please check if it compiles now. I don't have a system with CUDA 9.1 at hand right now to check.

**Comment by sina-masnadi** [comment]
@ashwin It works now! Thank you
