### ISSUE TITLE
Failure to build

### ISSUE THREAD

**Issue by Codeguyross** [ashwin/gDel3D#8]
I tried several different methods of building this library and all have resulted in the following error. I thought that maybe if I used the nvidia docker container and tried to build the library from within there that it would be, but that didnt work either. I always end up with the "thrust" has no member "device_malloc". any ideas?

make
[  7%] Building NVCC (Device) object CMakeFiles/gflip3d.dir/GDelFlipping/src/gDel3D/GPU/gflip3d_generated_ThrustWrapper.cu.o
/home/gDel3D/GDelFlipping/src/gDel3D/GPU/ThrustWrapper.cu(121): error: namespace "thrust" has no member "device_malloc"

/home/gDel3D/GDelFlipping/src/gDel3D/GPU/ThrustWrapper.cu(121): error: type name is not allowed

/home/gDel3D/GDelFlipping/src/gDel3D/GPU/ThrustWrapper.cu(121): error: expression must have class type

/home/gDel3D/GDelFlipping/src/gDel3D/GPU/GPUDecl.h(280): error: namespace "thrust" has no member "device_malloc"

/home/gDel3D/GDelFlipping/src/gDel3D/GPU/GPUDecl.h(280): error: type name is not allowed

5 errors detected in the compilation of "/tmp/tmpxft_00000a74_00000000-7_ThrustWrapper.compute_30.cpp1.ii".
CMake Error at gflip3d_generated_ThrustWrapper.cu.o.Release.cmake:279 (message):
  Error generating file
  /home/gDel3D/build/CMakeFiles/gflip3d.dir/GDelFlipping/src/gDel3D/GPU/./gflip3d_generated_ThrustWrapper.cu.o

CMakeFiles/gflip3d.dir/build.make:84: recipe for target 'CMakeFiles/gflip3d.dir/GDelFlipping/src/gDel3D/GPU/gflip3d_generated_ThrustWrapper.cu.o' failed
make[2]: *** [CMakeFiles/gflip3d.dir/GDelFlipping/src/gDel3D/GPU/gflip3d_generated_ThrustWrapper.cu.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/gflip3d.dir/all' failed
make[1]: *** [CMakeFiles/gflip3d.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Codeguyross** [comment]
This issue was related to having the version 10.2 of cuda. I witch to cuda 9.1 and this error went away

**Comment by harrydobbs** [comment]
Any chance that this package is going to support newer versions of CUDA @ashwin ?
Thank you :)

**Comment by ashwin** [comment]
@harry1576 Sadly, no. I just don't have the time. If you can make it work and give a PR, I would be happy to review and merge it.

**Comment by harrydobbs** [comment]
Okay no worries that is understandable. I don't have much experience in CUDA programming, do you have any advice on a good place to start?
